# Generated by Django 5.2.17 on 2026-09-17 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('sku_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('product_category', models.CharField(max_length=60)),
                ('shop_id', models.CharField(default='SHOP-DEMO', max_length=32)),
                ('demo_scenario', models.CharField(blank=True, help_text="Which PRD demo scenario this SKU's dummy data illustrates.", max_length=60)),
            ],
            options={
                'ordering': ['sku_id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_mode', models.CharField(choices=[('PRODUCTION', 'Production'), ('REPLENISHMENT', 'Replenishment')], max_length=20)),
                ('constraint_profile', models.CharField(choices=[('FOOD_DEMO', 'Food demo'), ('FASHION', 'Fashion'), ('BEAUTY', 'Beauty'), ('ELECTRONICS', 'Electronics')], max_length=20)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_variable_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('production_minutes_per_unit', models.FloatField(blank=True, null=True)),
                ('material_per_unit', models.FloatField(blank=True, null=True)),
                ('supplier_lead_time_hours', models.FloatField(blank=True, null=True)),
                ('minimum_commitment', models.PositiveIntegerField(default=0)),
                ('shelf_life_hours', models.FloatField(blank=True, null=True)),
                ('salvage_value_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_capacity_minutes', models.FloatField(help_text='Shop-level production/handling capacity per day.')),
                ('working_capital_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commitment_deadline', models.DateTimeField()),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_config', to='skus.sku')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('orders_cancelled_pre_ship', models.PositiveIntegerField(default=0)),
                ('orders_shipped', models.PositiveIntegerField(default=0)),
                ('orders_delivered', models.PositiveIntegerField(default=0)),
                ('orders_returned', models.PositiveIntegerField(default=0)),
                ('stock_on_hand', models.IntegerField(default=0)),
                ('incoming_stock', models.IntegerField(default=0)),
                ('stockout_flag', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promotion_flag', models.BooleanField(default=False)),
                ('product_views', models.PositiveIntegerField(blank=True, null=True)),
                ('affiliate_orders', models.PositiveIntegerField(blank=True, null=True)),
                ('active_affiliates', models.PositiveIntegerField(blank=True, null=True)),
                ('content_view_velocity', models.FloatField(blank=True, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='skus.sku')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['sku', 'timestamp'], name='skus_hourly_sku_id_21d0f2_idx')],
                'unique_together': {('sku', 'timestamp')},
            },
        ),
    ]
