# Generated by Django 5.2.17 on 2026-09-17 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_action', models.CharField(max_length=32)),
                ('commit_now_units', models.IntegerField()),
                ('commit_later_units', models.IntegerField()),
                ('required_capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_contribution', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan_drafts', to='skus.sku')),
            ],
            options={
                'ordering': ['-approved_at'],
            },
        ),
    ]
